name = "sigmund"
description = "Personal theme for my Zola blog."
min_version = "0.16.0"
license = "MIT"
homepage = "https://github.com/videah/sigmund"

# Any variable there can be overridden in the end user `config.toml`
# You don't need to prefix variables by the theme name but as this will
# be merged with user data, some kind of prefix or nesting is preferable
# Use snake_casing to be consistent with the rest of Zola
[extra]

[author]
name = "videah"
homepage = "https://github.com/videah"